name: proteins
channels:
  - conda-forge
  - schrodinger # pymol
  - bioconda    # clustal, muscle, blast
  - salilab     # dssp
  - defaults
dependencies:
  # Basic
  - pip
  - python=3.8.*
  # Development
  - black
  - ipython
  - jupyter
  - jupyterlab
  - nodejs
  - pre-commit
  - pytest
  - pytest-benchmark
  - pytest-cov
  - pytest-repeat
  - pytest-xdist
  # Project Dependencies
  - biopython
  - blast
  - clustalo
  - dssp
  - matplotlib
  - more-itertools
  - muscle
  - nglview
  - numba
  - numpy
  - pandas
  - pymol-bundle
  - requests
  - scikit-learn
  - toml
  - tqdm
  - uncertainties
  # pip dependencies
  - pip:
    - nbmerge
    - -e .  # install this package
