name: proteins
channels:
  - schrodinger # pymol
  - bioconda    # clustal, muscle, blast
  - salilab     # dssp
  - conda-forge
  - defaults
dependencies:
  - python=3.8.*
  - pymol-bundle
  - biopython
  - ipython
  - jupyter
  - jupyterlab
  - requests
  - nodejs
  - numpy
  - scikit-learn
  - pandas
  - pytest
  - pytest-benchmark
  - pytest-repeat
  - pytest-xdist
  - pytest-cov
  - pre-commit
  - black
  - tqdm
  - matplotlib
  - numba
  - hdf5
  - h5py
  - yattag
  - uncertainties
  - muscle
  - clustalo
  - blast
  - dssp
  - nglview
  - pip
  - pip:
    - nbmerge
    - -e . # install this package
