name: proteins
channels:
  - defaults
  - conda-forge
  - schrodinger # pymol
  - bioconda    # clustal, muscle, blast
  - salilab     # dssp
dependencies:
  # Note about pymol: On macos 10.15 installing pymol from conda seems to work but
  # then pymol fails to start.
  # To fix it, after installing this env, we need to do:
  # conda uninstall -y pymol-bundle && conda install -y --force-reinstall -c schrodinger pymol-bundle=2.4.1
  - python=3.8.6
  - pymol-bundle=2.4.1
  - biopython=1.78
  - ipython
  - jupyter
  - jupyterlab
  - requests
  - nodejs
  - numpy
  - scikit-learn
  - pandas
  - pytest
  - pytest-benchmark
  - pytest-repeat
  - pytest-xdist
  - pytest-cov
  - pre-commit
  - black
  - tqdm
  - matplotlib
  - numba
  - hdf5
  - h5py>=2.10
  - yattag
  - uncertainties
  - muscle
  - clustalo
  - blast
  - dssp
  - pip
  - pip:
    - nbmerge
  - nglview