name: proteins
channels:
  - defaults
  - conda-forge
  - schrodinger # pymol
  - bioconda    # clustal, muscle, blast
  - salilab     # dssp
dependencies:
  - python=3.8.3
  - ipython>=7.9
  - jupyter
  - jupyterlab
  - requests
  - nodejs
  - numpy
  - scikit-learn
  - pandas
  - pytest
  - pytest-benchmark
  - pytest-repeat
  - pytest-xdist
  - tqdm
  - matplotlib
  - numba
  - hdf5
  - h5py>=2.10
  - yattag
  - uncertainties
  - pymol
  - muscle
  - clustalo
  - blast
  - dssp
  - pip
  - pip:
    - nbmerge
    # Use a development version of biopython due to bug with parsing swissprot
    # https://github.com/biopython/biopython/issues/2417
    - git+https://github.com/biopython/biopython.git@a010428309c4bf7f4c9be7c36a01ad62d9bb8e94
