name: proteins
channels:
  - schrodinger # pymol
  - bioconda    # clustal, muscle, blast
  - salilab     # dssp
  - conda-forge
  - defaults
dependencies:
  # Basic
  - pip
  - python=3.8.*
  # Development
  - black
  - ipython
  - jupyter
  - jupyterlab
  - nodejs
  - pre-commit
  - pytest
  - pytest-benchmark
  - pytest-cov
  - pytest-repeat
  - pytest-xdist
  # Project Dependencies
  - biopython
  - blast
  - clustalo
  - dssp
  - h5py
  - hdf5
  - matplotlib
  - muscle
  - nglview
  - numba
  - numpy
  - pandas
  - pymol-bundle
  - requests
  - scikit-learn
  - tqdm
  - uncertainties
  # pip dependencies
  - pip:
    - nbmerge
    - --no-deps -e . # install this package
