[tool.pytest.ini_options]
addopts = "--cov pp5 --cov-report term-missing --verbose -n 4"
testpaths = [
    "tests",
]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
length_sort = true
# There's some weirdness between pymol and biopython: seems like it pymol must
# be imported after biopython for some unknown reason, otherwise it pymol's
# __init__ fails.  This fixes the issue by createing a section specifically for
# pymol after all the third-party stuff.
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'PYMOL', 'FIRSTPARTY', 'LOCALFOLDER']
known_pymol = ['pymol']

[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | data
    | out
  )/
  | __foo__.py           # also separately exclude a specific file (example)
)
'''
